name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Build and test Spring Boot
        run: |
          cd transfer/transfer-api
          ./mvnw clean install  # Use ./mvnw se você estiver usando o wrapper do Maven

  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd transfer/transfer-ui
          npm install

      - name: Build and test Angular
        run: |
          cd transfer/transfer-ui
          npm run test -- --watch=false  # Execute os testes do Angular
