name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Altere para o nome do branch que você deseja monitorar
  pull_request:
    branches:
      - master

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/transfer-api/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test Spring Boot
        run: |
          cd transfer-api
          ./mvnw clean install || { echo 'Backend build failed'; exit 1; }

  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Altere para a versão do Node.js que você está utilizando

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/transfer-ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          cd transfer-ui
          npm install

      - name: Build and test Angular
        run: |
          cd transfer-ui
          npm run build || { echo 'Frontend build failed'; exit 1; }
          npm run test -- --watch=false --bail
