name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Altere para o nome do branch que você deseja monitorar
  pull_request:
    branches:
      - master

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: temurin # Mudado para temurin (nova distribuição do JDK da Adoptium)
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/transfer-api/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Grant execute permission for mvnw
        run: chmod +x ./transfer-api/mvnw

      - name: Build and test Spring Boot
        run: |
          cd transfer-api
          ./mvnw clean install || { echo 'Backend build failed'; exit 1; }

  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Altere para a versão do Node.js que você está utilizando

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/transfer-ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          cd transfer-ui
          npm install

      - name: Build Angular app
        run: |
          cd transfer-ui
          npm run build || { echo 'Frontend build failed'; exit 1; }

      - name: Run tests (Headless Chrome)
        run: |
          cd transfer-ui
          npm run test -- --watch=false --browsers=ChromeHeadless --no-progress || { echo 'Frontend tests failed'; exit 1; }
